apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  # minReadySeconds: 30
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:4
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db

      volumes:
        - name: mongo-persistent-storage
          # Pointer to the configuration of how we want to mount to be implemented
          persistentVolumeClaim:
            claimName: mongo-persistent-volume-claim

---
# kind: Service
# apiVersion: v1
# metadata:
#   name: pizza-mongodb
# spec:
#   type: NodePort
#   selector:
#     app: mongodb
#   ports:
#     - port: 27017
#       # targetPort: 27017
#       nodePort: 30017


apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017