# local storage - mongo-persistent-volume-claim
# what do we want
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-persistent-volume-claim
spec:
  storageClassName: tgalocalstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# how do we want to implemented
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  storageClassName: tgalocalstorage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/db/path"
    type: DirectoryOrCreate